[package]
name = "twsearch-ffi"
version.workspace = true
license.workspace = true
edition.workspace = true
description = "Twizzle Search FFI — C FFI bindings for twsearch"

[features]
default = []

[dependencies]
twsearch = { path = "../rs", version = "0.6.4" }

[lib]
path = "./lib.rs"
crate-type = ["cdylib"]

[dev-dependencies]
cubing = "0.7.3"
libloading = "0.8.1"
test-cdylib = "1.1.0"
