[workspace]
resolver = "2"

members = [
  "src/cpp",
  "src/rs",
  "src/rs-ffi",
  "src/rs-wasm",
]
default-members = [
  "src/rs"
]

[workspace.package]
version = "0.6.5"
license = "MPL-2.0"
edition = "2021"

[workspace.dependencies]
cubing = { version = "0.12.3" }

[workspace.metadata.bin]
cbindgen = { version = "0.26.0" }
cargo-binstall = { version = "1.4.4" }
