[package]
name = "twsearch"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
clap_complete = "4.2.1"
cubing = "0.3.0"
cxx = "1.0"
lazy_static = "1.4.0"
num_cpus = "1.15.0"
regex = "1.8.1"
rouille = "3.6.2"
serde = { version = "1.0.160", features = ["derive", "rc"] }

[build-dependencies]
cxx-build = "1.0"

[[bin]]
name = "twsearch-rs"
path = "./src/rs/main.rs"
