[package]
name = "twsearch"
version = "0.0.0"
edition = "2021"

[features]
default = []
orientation_packer = []
no_orientation_mod = []

[dependencies]
cityhash = "0.1.1"
cubing = "0.5.4"
derive_more = "0.99.17"

[dev-dependencies]
wait-timeout = "0.2.0"

[lib]
name = "twsearch"
path = "./mod.rs"
