[package]
name = "twsearch"
version = "0.0.0"
edition = "2021"

[features]
default = []
console_error_panic_hook = []

[dependencies]
cityhasher = "0.1.0"
clap = { version = "4.3.24", features = ["derive"] }
clap_complete = "4.3.2"
console_error_panic_hook = "0.1.7"
cubing = { version = "0.7.3" }
derive_more = "0.99.17"
indicatif = "0.17.6"
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
rand = "0.8.5"
rouille = "3.6.2"
serde = { version = "1.0.186", features = ["derive", "rc"] }
serde_json = "1.0.105"
thousands = "0.2.0"
wasm-bindgen = "0.2.87"

[dev-dependencies]
wait-timeout = "0.2.0"

[[bin]]
name = "twsearch"
path = "./cli/main.rs"

[lib]
path = "./mod.rs"
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.lib]
path = "./wasm/mod.rs"

[dependencies.getrandom]
features = ["js"]

[package.metadata.wasm-pack.profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
# Should we emit the DWARF debug info custom sections?
dwarf-debug-info = false
