[package]
name = "twsearch"
version = "0.0.0"
edition = "2021"

[features]
default = ["orientation_packer"]
orientation_packer = []
no_orientation_mod = []

[dependencies]
cityhash = "0.1.1"
clap = { version = "4.3.24", features = ["derive"] }
clap_complete = "4.3.2"
cubing = "0.6.0"
derive_more = "0.99.17"
serde = { version = "1.0.186", features = ["derive", "rc"] }
serde_json = "1.0.105"

[dev-dependencies]
wait-timeout = "0.2.0"

[lib]
path = "./mod.rs"

[[bin]]
name = "twsearch"
path = "./cli/main.rs"
