name: make build

on: [push, pull_request]

jobs:
  cpp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: make
      - run: ./build/bin/twsearch -g samples/main/2x2x2.tws

  wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: make emsdk
      - run: make build/wasm-test/twsearch-test.wasm
      - run: make build/wasm-single-file/twsearch.mjs
      - run: curl https://get.wasmer.io -sSfL | sh
      - run: source ~/.wasmer/wasmer.sh && wasmer build/wasm-test/twsearch-test.wasm
      - run: make test-build-js
