name: make build

on: [push, pull_request]

jobs:
  cpp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: make
      - run: ./build/bin/twsearch -g samples/main/2x2x2.tws

  wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: make build/wasm-raw/twsearch.wasm
      - run: make build/wasm-wrapped/twsearch.wasm
      - run: curl https://get.wasmer.io -sSfL | sh
      - run: source /home/runner/.wasmer/wasmer.sh && wasmer build/wasm-raw/twsearch.wasm
